# Generated by Django 3.0.7 on 2020-09-06 10:01

import clglib.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('total_copies', models.IntegerField(default=1000)),
                ('available_copies', models.IntegerField(default=1000)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_image')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_no', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('issuedate', models.DateTimeField(auto_now=True)),
                ('returndate', models.DateTimeField(default=clglib.models.get_expiry)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_no', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Prefer not to say', 'Prefer not to say')], default='none', max_length=20)),
                ('branch', models.CharField(choices=[('Computer Science & Engineering (CSE)', 'Computer Science & Engineering (CSE)'), ('Electronics & Communication Engineering (ECE)', 'Electronics & Communication Engineering (ECE)'), ('Electrical and Electronics Engineering (EEE)', 'Electrical and Electronics Engineering (EEE)'), ('Mechanical Engineering (ME)', 'Mechanical Engineering (ME)'), ('Civil Engineering (CE)', 'Civil Engineering (CE)'), ('Chemical Engineering (ChE)', 'Chemical Engineering (ChE)'), ('Master of Business Administration (MBA)', 'Master of Business Administration (MBA)')], default='none', max_length=50)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
