# Generated by Django 3.0.7 on 2020-09-06 16:30

import clglib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clglib', '0002_auto_20200906_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issuedate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='returndate',
            field=models.DateTimeField(default=clglib.models.get_expiry),
        ),
    ]
